# @package _global_

defaults:
  - _self_
  - data: satsemseg # choose datamodule with `test_dataloader()` for evaluation
  - model: satsemseg
  - callbacks: null
  - logger: aim
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  # experiment configs override data/model settings to match a training run
  - experiment: null

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
